# Generated by Django 4.2.25 on 2025-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32)),
                ('gateway', models.CharField(max_length=20)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('process_url', models.URLField(blank=True)),
                ('status', models.CharField(default='created', max_length=32)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['order_number'], name='payments_pa_order_n_d27165_idx')],
            },
        ),
    ]
