# Generated by Django 4.2.25 on 2025-11-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_order_n_d27165_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('placetopay', 'PlaceToPay'), ('otro', 'Otro')], default='placetopay', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_number',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='payment',
            name='process_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='created', max_length=64),
        ),
    ]
