# Generated by Django 4.2.25 on 2025-11-22 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_image_file_product_image_local_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_name_39f70b_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_slug_695af4_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_name_f603c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_slug_2b1eb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_is_acti_14fc6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_categor_7c1c1f_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_local',
            new_name='image_file',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen RAW (GitHub/DO)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_crc',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio (CRC)'),
        ),
    ]
