# Generated by Django 4.2.25 on 2025-11-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_fix_image_fields'),
    ]

    operations = [
    ]
