# Generated by Django 4.2.25 on 2025-10-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('sinpe', 'SINPE'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20, verbose_name='Método de pago')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Comprobante (opcional)')),
                ('total_crc', models.PositiveIntegerField(default=0, verbose_name='Total en CRC')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price_crc', models.PositiveIntegerField(default=0, verbose_name='Precio unidad CRC')),
                ('total_crc', models.PositiveIntegerField(default=0, verbose_name='Total línea CRC')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
    ]
